app:
  intervalo-job-minutos: ${INTERVALO_JOB_MINUTOS:1}
  whitelist:
    url: ${WHITELIST_URL:https://run.mocky.io/v3/57f23672-c15f-48f8-90d3-d84ce00250b8/users}
    ativado: ${WHITELIST_ATIVADO:false}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:develop}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  messages:
    basename: i18n/messages
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer