spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: develop
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ## Enable hibernate debug query
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  messages:
    basename: i18n/messages